wasm:
    wasm-pack build -t no-modules -d ../frontend/wasm/ --no-typescript

wasm-opt:
    wasm-pack build -t no-modules -d ../frontend/wasm/ --no-typescript 
    wasm-opt -O3 ../frontend/wasm/proc_bg.wasm -o ../frontend/wasm/proc_bg.wasm